apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app-pod: {{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        app-pod: {{ .Release.Name }}-pod
    spec:
        containers:
        - name: app-container
          image: nginx # the version does not matter for now
          ports:
          - containerPort: 80 # this is the port nginx is listening on
            name: app-port
          volumeMounts:
          - name: custom-docroot
            mountPath: /usr/share/nginx/html
        volumes:
        - name: custom-docroot
          hostPath:
            path: /tmp
            type: Directory  