apiVersion: v1
kind: Service # with default type of ClusterIP
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app-pod: {{ .Release.Name }}-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: app-port